[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russenger = { version = "0.3.6-rc", features = ["sqlite"] }
actix-web = "4"
sqlx = "0.8.0"
